<?php

namespace PW\PortfolioBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkillGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillGroupRepository extends EntityRepository
{
}
