pw_portfolio:
    resource: "@PWPortfolioBundle/Resources/config/routing.yml"
    prefix:   /test

login:
    pattern:   /login
    defaults:  { _controller: PWUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

pw_user:
    resource: "@PWUserBundle/Resources/config/routing.yml"
    prefix: /
