pw_user_homepage:
    pattern: /User
    defaults: { _controller: PWUserBundle:Security:index }

pw_user_profile:
    pattern: /User/Profile
    defaults: { _controller: PWUserBundle:Security:profile}

pw_user_catalogue:
    pattern: /User/Catalogue
    defaults: { _controller: PWUserBundle:Security:catalogue}