PW\PortfolioBundle\Entity\Skill:
    type: entity
    table: null
    repositoryClass: PW\PortfolioBundle\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        skillName:
            type: string
            length: 255
            column: Skill_Name

        skillMastery:
            type: string
            length: 255
            column: Skill_Mastery
    lifecycleCallbacks: {  }
