PW\PortfolioBundle\Entity\Training:
    type: entity
    table: null
    repositoryClass: PW\PortfolioBundle\Repository\TrainingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nameTraining:
            type: string
            length: 255
        qualification:
            type: string
            length: 255
        trainingDescriptive:
            type: string
            length: 255
        date:
            type: date
        adress:
            type: string
            length: 255
        user:
            type: string
            length: 255
    lifecycleCallbacks: {  }
