pw_portfolio_homepage:
    path:    /test
    defaults: { _controller: PWPortfolioBundle:Portfolio:test }

pw_portfolio_home:
    path:    /portfolio
    defaults: { _controller: PWPortfolioBundle:Portfolio:index }

pw_portfolio_information:
    path:    /portfolio/information
    defaults: { _controller: PWPortfolioBundle:Portfolio:information }

pw_portfolio_introduction:
    path:    /portfolio/introduction
    defaults: { _controller: PWPortfolioBundle:Portfolio:introduction }

pw_portfolio_ergonomy:
    path:    /portfolio/ergonomy
    defaults: { _controller: PWPortfolioBundle:Portfolio:ergonomy }

pw_portfolio_apercu:
    path:    /portfolio/apercu/{app.user}
    defaults: { _controller: PWPortfolioBundle:Portfolio:apercu }

pw_portfolio_competence:
    path:    /portfolio/competence
    defaults: { _controller: PWPortfolioBundle:Portfolio:training }

pw_portfolio_experience:
    path:    /portfolio/experience
    defaults: { _controller: PWPortfolioBundle:Portfolio:experience }

pw_portfolio_projet:
    path:    /portfolio/projet

    defaults: { _controller: PWPortfolioBundle:Portfolio:projet }
