pw_portfolio_homepage:
    path:     /
    defaults: { _controller: PWPortfolioBundle:Portfolio:index }

pw_portfolio_home:
    path: /portfolio
    defaults: { _controller: PWPortfolioBundle:Portfolio:index }
